# Generated by Django 5.1.4 on 2024-12-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
