# Generated by Django 5.1.4 on 2025-01-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackServer', '0002_user_is_admin_user_secret_data_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
