# Generated by Django 5.1.4 on 2025-01-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackServer', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
